### ISSUE TITLE
修改和删除按键点了没反应,报错如下:

### ISSUE THREAD

**Issue by jinbao55** [lin5572545/Book#1]
_Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at o.<anonymous> (question:97:38)
    at c (layui.js:2:1690)
    at g (layui.js:2:2249)
    at o.use (layui.js:2:2270)
    at deleteQuestion (question:94:15)
    at HTMLAnchorElement.onclick (question:1:1)_

**Comment by acherlin** [comment]
你得先选中左边的复选框之后才能修改
